START = program
program = class* main

main = "MAIN" body
class = "CLASS" name body

body = "{" const* declaration* assign* "}"

const = "CONST" type name "=" value ";"
declaration = "VAR" type name ";"
assign = name "=" expr ";"

expr = term o_term*
o_term = t_o term
t_o = "+" | "-"
term = factor o_factor*
o_factor = f_o factor
f_o = "*" | "/"
factor = bracket_expr | value | name
bracket_expr = "(" expr ")"


